# Generated by Django 2.1.5 on 2019-01-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crontab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=100)),
                ('channel_id', models.CharField(help_text='Slack internal channel ID, will be automatically set based on channel_name', max_length=30)),
                ('gerrit_query', models.CharField(blank=True, max_length=255)),
                ('crontab', models.CharField(help_text='Examples: <a href="https://crontab.guru/" target="_blank">crontab.guru<a>', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(help_text='The message ts of the requests', max_length=30)),
                ('slack_user_id', models.CharField(help_text='The Slack user who sent the request', max_length=30)),
                ('channel_id', models.CharField(help_text='The channel where this requests is sent to originally', max_length=30)),
                ('gerrit_url', models.URLField()),
                ('gerrit_query', models.CharField(blank=True, max_length=255)),
                ('crontab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='slackbot.Crontab')),
            ],
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=30)),
                ('channel_id', models.CharField(max_length=30)),
                ('message', models.TextField(help_text='JSON serialized slack response "message" field to a chat.PostMessage')),
                ('crontab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='slackbot.Crontab')),
            ],
        ),
    ]
