# Generated by Django 2.0.2 on 2018-02-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crontab',
            name='channel_id',
            field=models.CharField(blank=True, help_text='Slack internal channel ID, will be automatically set based on channel_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='crontab',
            name='crontab',
            field=models.CharField(help_text='Examples: <a href="https://crontab.guru/" target="_blank">crontab.guru<a>', max_length=255),
        ),
    ]
