# Generated by Django 2.1.2 on 2018-10-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0004_auto_20181031_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(help_text='The message ts of the requests', max_length=30)),
                ('slack_user_id', models.CharField(help_text='The Slack user who sent the request', max_length=30)),
                ('channel_id', models.CharField(help_text='The channel where this requests is sent to originally', max_length=30)),
                ('gerrit_url', models.URLField()),
                ('gerrit_query', models.CharField(blank=True, max_length=255)),
                ('crontab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requests', to='slackbot.Crontab')),
            ],
        ),
    ]
